# permissions for end users to edit tortoises.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tortoise-editor-role
rules:
- apiGroups:
  - autoscaling.sanposhiho.com
  resources:
  - tortoises
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - autoscaling.sanposhiho.com
  resources:
  - tortoises/status
  verbs:
  - get
