# permissions for end users to view tortoises.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tortoise-viewer-role
rules:
- apiGroups:
  - autoscaling.sanposhiho.com
  resources:
  - tortoises
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - autoscaling.sanposhiho.com
  resources:
  - tortoises/status
  verbs:
  - get
